[package]
name = "use_static_lib"
version = "0.1.0"
authors = ["Phuwadon Verasertniyom <phuwadonpeak@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
static_lib = { path = "../static_lib" }