[package]
name = "use_dynamic_lib"
version = "0.1.0"
authors = ["Phuwadon Verasertniyom <phuwadonpeak@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
dynamic_lib = { path = "../dynamic_lib" }